# Cloud Build configuration for NVIDIA Cert Quiz Backend
# Deploy to Cloud Run in asia-northeast3 (Seoul)

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/nvidia-cert-quiz/backend:latest'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/nvidia-cert-quiz/backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nvidia-cert-quiz-api'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/nvidia-cert-quiz/backend:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--set-secrets'
      - 'SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest,OPENAI_API_KEY=openai-api-key:latest'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
